[[main]]
name = "Sobre mí"
url = "/#about"
weight = 2

[[main]]
name = "Habilidades"
url = "/#skills"
weight = 3

[[main]]
name = "Experiencia"
url = "/#experience"
weight = 4

[[main]]
name = "Contacto"
url = "/#contact"
weight = 5

[[main]]
name = "Tech Stack"
url = "/#technical"
weight = 4.5

[[main]]
name = "Blog"
pageRef = "/blog"
weight = 60

[[main]]
name = "Ingeniería"
pageRef = "/engineering"
weight = 50
pre = "engineering"

[[main]]
name = "Contribuciones"
pageRef = "/contributions"
weight = 51
pre = "contributions"

