baseURL = "https://felipecordero.com"
languageCode = "en-us"
title = "Felipe Cordero"
theme = "careercanvas"

[build]
  writeStats = true

[params]
name = "Felipe Cordero"
tagline = "Engineer. Coder. Problem Solver."
location = "Montréal, Canada"
email = "mail@felipecordero.com"
profile_image = "/images/felipe-cordero-profile.jpeg"
description = "Structural engineer and AI developer solving real-world problems in construction tech."
author = "Felipe Cordero"

og_image = "images/felipe-cordero-og.png"

hero_description = "Structural engineer and software developer combining 14+ years in AEC with AI/ML expertise to build smarter construction tech solutions."
hero_location = "Montréal, Canada"

linkedin_url = "https://www.linkedin.com/in/felipe-cordero-osorio"
linkedin_text = "linkedin.com/in/felipe-cordero-osorio"
github_url = "https://github.com/felipecordero"
github_text = "github.com/felipecordero"

copyright = "© 2025 | Felipe Cordero"

collab_tags = [
  "AI/ML Solutions",
  "Engineering Software",
  "R&D & Innovation",
  "Technical Leadership",
  "Construction Tech"
]

resume_url_en = "/files/Felipe_Cordero_CV_English_version.pdf"
resume_url_fr = "/files/Felipe_Cordero_CV_French_version.pdf"
resume_label = "Download Full Resume"

[[params.social]]
icon = "linkedin-in"
url = "https://www.linkedin.com/in/felipe-cordero-osorio/"

[[params.social]]
icon = "github"
url = "https://github.com/felipecordero"

sectionPagesMenu = 'main'

[[menu.main]]
  name = "Experience"
  url = "/#experience"
  weight = 4

[[menu.main]]
  name = "About"
  url = "/#about"
  weight = 2

[[menu.main]]
  name = "Skills"
  url = "/#skills"
  weight = 3

[[menu.main]]
  name = "Experience"
  url = "/#experience"
  weight = 4

[[menu.main]]
  name = "Contact"
  url = "/#contact"
  weight = 5

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 60

[[menu.main]]
  name = "Technical Skills"
  url = "/#technical"
  weight = 4.5

[taxonomies]
  tag = "tags"

[markup.goldmark.renderer]
unsafe = true

[menu]
  [[menu.main]]
    name = "Structural Engineering"
    url = "/engineering/"
    weight = 50
    pre = "engineering"
  [[menu.main]]
    name = "Contributions"
    url = "/contributions/"
    weight = 51
    pre = "contributions"




