baseURL = "https://felipecordero.com"
languageCode = "en-us"
title = "Felipe Cordero"
theme = "careercanvas"

[build]
  writeStats = true

[params]
name = "Felipe Cordero"
tagline = "Engineer. Coder. Problem Solver."
location = "Montréal, Canada"
email = "mail@felipecordero.com"
profile_image = "/images/felipe-cordero-linkedin.png"
description = "Structural engineer and software developer expanding into AI/ML to solve complex engineering and automation challenges."
author = "Felipe Cordero"

og_image = "images/felipecordero-og.png"

hero_description = "Structural engineer and software developer with 14+ years in Architecture, Engineering, and Construction (AEC), expanding expertise with AI/ML to build intelligent solutions for complex engineering problems."
hero_location = "Montréal, Canada"

linkedin_url = "https://www.linkedin.com/in/felipe-cordero-osorio"
linkedin_text = "linkedin.com/in/felipe-cordero-osorio"
github_url = "https://github.com/felipecordero"
github_text = "github.com/felipecordero"

copyright = "© 2025 | Felipe Cordero"

collab_tags = [
  "AI/ML Solutions",
  "Engineering Software",
  "R&D & Innovation",
  "Technical Leadership",
  "Construction Tech"
]

resume_url_en = "/files/Felipe_Cordero_CV_English_version.pdf"
resume_url_fr = "/files/Felipe_Cordero_CV_French_version.pdf"
resume_label = "View CV"

formspree_endpoint = "https://formspree.io/f/xgvkkdnn" # Change to your Formspree endpoint

# Technical skills configuration
[params.technical_skills]
# FontAwesome brand icons (for special icons like Python, JS, etc.)
brand_icons = ["python", "js", "html5", "css3-alt", "linux", "docker", "github", "gitlab"]

[[params.social]]
icon = "linkedin-in"
url = "https://www.linkedin.com/in/felipe-cordero-osorio/"

[[params.social]]
icon = "github"
url = "https://github.com/felipecordero"

sectionPagesMenu = 'main'

[[menu.main]]
  name = "Experience"
  url = "/#experience"
  weight = 4

[[menu.main]]
  name = "About"
  url = "/#about"
  weight = 2

[[menu.main]]
  name = "Skills"
  url = "/#skills"
  weight = 3

[[menu.main]]
  name = "Experience"
  url = "/#experience"
  weight = 4

[[menu.main]]
  name = "Contact"
  url = "/#contact"
  weight = 5

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 60

[[menu.main]]
  name = "Technical Skills"
  url = "/#technical"
  weight = 4.5

[taxonomies]
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokai"

[server]
  [[server.headers]]
    for = "/**/*.css"
    [server.headers.values]
      Content-Type = "text/css"

[menu]
  [[menu.main]]
    name = "Structural Engineering"
    url = "/engineering/"
    weight = 50
    pre = "engineering"
  [[menu.main]]
    name = "Contributions"
    url = "/contributions/"
    weight = 51
    pre = "contributions"




