name = "CareerCanvas"
license = "MIT"
licenselink = "https://github.com/felipecordero/hugo_site/blob/main/LICENSE"
description = "A modern, responsive Hugo theme for personal websites and portfolios"
homepage = "https://github.com/felipecordero/hugo_site"
tags = ["blog", "portfolio", "personal", "responsive", "modern", "career", "resume"]
features = ["responsive", "blog", "portfolio", "dark mode", "resume", "career showcase"]
min_version = "0.68.0"

[author]
  name = "Felipe Cordero"
  homepage = "https://felipecordero.com" 